In [ ]:
import numpy as np

a = np.array([1, 2, 3])          # 1D array
b = np.array([[1, 2], [3, 4]])   # 2D array
c = np.zeros((2,3))              # 2x3 array of zeros
d = np.ones((3,3))               # 3x3 array of ones
e = np.arange(0, 10, 2)          # [0 2 4 6 8]
f = np.linspace(0, 1, 5)         # [0. 0.25 0.5 0.75 1.]


Indexing and slicing

In [9]:
import numpy as np

nums = np.array([0])

for i in range(1,10):
    nums=np.append(nums,i)

print(nums)

nums[1::2]

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [10]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])

adotb=np.dot(a,b)

print(adotb)


60


In [11]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])


In [12]:
print(A.T)
# [[1 3]
#  [2 4]]


[[1 3]
 [2 4]]


3. Matrix Multiplication

⚠️ In NumPy:

A * B → element-wise multiply

A @ B or np.dot(A,B) → matrix multiply

In [15]:
print(A @ B)
# [[19 22]
#  [43 50]]

print(A*B)

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [16]:
print(np.linalg.inv(A))   # inverse
print(np.linalg.det(A))   # determinant


[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [17]:
vals, vecs = np.linalg.eig(A)
print("Eigenvalues:", vals)
print("Eigenvectors:\n", vecs)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [20]:
#defin the matrix M

M = np.array([[2, 1],
              [1, 2]])

detM=np.linalg.det(M)
print(detM)

invM=np.linalg.inv(M)
print(invM)

eigvalM,eigvecM=np.linalg.eig(M)
print(eigvalM)
print(eigvecM)

2.9999999999999996
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
